
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/foodmap?serverTimezone=UTC&characterEncoding=UTF-8
      username: foodmap
      password: java1234
      driver-class-name: com.mysql.cj.jdbc.Driver

  server:
    port: 8095