spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodmap?serverTimezone=UTC&characterEncoding=UTF-8
    username: foodmap
    password: java1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 8095

file:
  image:
    path: C:\foodmap\image\

credential:
  keys:
    firebase-full-path: C:\foodmap\keys\firebase\foodmap-1e013-firebase-adminsdk-5h5pi-8188cb2e63.json

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
