
  spring:
    datasource:
      url: jdbc:log4jdbc:mysql://localhost:3306/foodmap?serverTimezone=UTC&characterEncoding=UTF-8
      username: foodmap
      password: java1234
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy


  server:
    port: 8095

  mybatis:
    type-aliases-package: pairproject.foodmap.dto
    mapper-locations: static/mapper/*.xml

  logging:
    level:
      root: INFO
      jdbc:
        sqlonly: DEBUG
        audit: off
        resultset: off
        connection: off


